development:
  password: ba276aa2691d8395a79c07553ad0fa8d
  theme_id: 7711293472
  store: marbektest.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
